name: cqrcode # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '1.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Create QR codes flying Canonical colors. # 79 char long summary
description: |
  cqrcode.create --help
  Usage: main.py [OPTIONS] URL

  Options:
  --output_file TEXT  Output file path (defaults to "./qrcode.png")
  --logo_path TEXT    Path to the logo to embed (defaults to the Canonical
  one)
  --help              Show this message and exit.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
platforms:
  amd64:
  arm64:
parts:
  venv:
    # See 'snapcraft plugins'
    plugin: python
    source-type: local
    source: .
    python-requirements:
      - requirements.txt
  source:
    plugin: dump
    source: .

apps:
  create:
    command: bin/python $SNAP/main.py 
    plugs:
      - home
